from collections.abc import Callable

from pulse.models import FeedResult

_REPO = "sm-ard/devops-pulse"


def _status_line(feed: FeedResult) -> str | None:
    if not feed.ok:
        return f"> ⚠ Feed unavailable today: {feed.error}"
    return None


def _section(title: str, feed: FeedResult, empty_msg: str,
             fmt: Callable[[object], str]) -> str:
    lines = [f"## {title}", ""]
    status = _status_line(feed)
    if status:
        lines += [status, ""]
    # Partial success: a feed with ok=False AND items renders both the
    # warning (above) and the items below.
    if feed.items:
        lines += [fmt(item) for item in feed.items]
    elif feed.ok:
        lines.append(empty_msg)
    lines.append("")
    return "\n".join(lines)


def _cve_line(i) -> str:
    return f"- **[{i.cve_id}]({i.url})** `{i.severity}` — {i.summary}"


def _release_line(i) -> str:
    return f"- **{i.tool}** [`{i.version}`]({i.url})"


def _news_line(i) -> str:
    return f"- [{i.title}]({i.url}) — _{i.source}_"


def _report_body(cve, releases, news) -> str:
    return "\n".join([
        _section("Security (CVEs)", cve, "No notable CVEs today.", _cve_line),
        _section("Releases", releases, "No notable releases today.", _release_line),
        _section("News", news, "No notable news today.", _news_line),
    ])


def build(date: str, cve: FeedResult, releases: FeedResult,
          news: FeedResult, archive_dates: list[str]) -> tuple[str, str]:
    body = _report_body(cve, releases, news)
    report = f"# DevOps Pulse — {date}\n\n{body}"

    archive = sorted(set(archive_dates), reverse=True)
    index = "\n".join(f"- [{d}](reports/{d}.md)" for d in archive) or "_No archived reports yet._"
    readme = (
        "# devops-pulse\n\n"
        "Daily, automated digest of real DevOps signal — new high/critical CVEs, "
        "cloud-native / DevOps tool releases, and k8s/cloud news. Generated by a scheduled GitHub "
        "Action; every commit is real published data.\n\n"
        f"![CI](https://github.com/{_REPO}/actions/workflows/ci.yml/badge.svg)\n\n"
        "---\n\n"
        f"## Latest — {date}\n\n"
        f"{body}\n"
        "---\n\n"
        "## Archive\n\n"
        f"{index}\n"
    )
    return report, readme
